import React, { useEffect, useState } from 'react';
import { useSearchParams, useNavigate } from 'react-router-dom';
import {
  CheckCircle2,
  XCircle,
  Building2,
  Calendar,
  Clock,
  Hash,
  Layers,
  ArrowLeft,
  Printer,
  ShieldCheck,
  GraduationCap
} from 'lucide-react';

export default function VerifyBooking() {
  const [searchParams] = useSearchParams();
  const navigate = useNavigate();
  const [booking, setBooking] = useState(null);
  const [error, setError] = useState(false);

  useEffect(() => {
    // Step 1: Read the 'data' query param from URL (e.g. /verify-booking?data=...)
    const raw = searchParams.get('data');
    if (!raw) {
      setError(true);
      return;
    }
    try {
      // Step 2: Decode the URI-encoded JSON string and parse it
      const parsed = JSON.parse(decodeURIComponent(raw));
      // Step 3: Validate that required fields exist
      if (!parsed.bookingId || !parsed.resourceName) {
        setError(true);
      } else {
        setBooking(parsed);
      }
    } catch (e) {
      // If JSON parsing fails, mark as invalid QR
      setError(true);
    }
  }, [searchParams]);

  const handlePrint = () => {
    window.print();
  };

  // ─────────────────────────────────────────────
  // INVALID QR STATE
  // ─────────────────────────────────────────────
  if (error) {
    return (
      <div style={{
        minHeight: '100vh',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        background: 'var(--bg)',
        padding: '24px'
      }}>
        <div style={{
          background: 'var(--surface)',
          border: '1px solid #fca5a5',
          borderRadius: '24px',
          padding: '48px',
          textAlign: 'center',
          maxWidth: '480px',
          width: '100%',
          boxShadow: 'var(--shadow-lg)'
        }}>
          <div style={{
            background: 'var(--danger-bg)',
            width: '80px',
            height: '80px',
            borderRadius: '50%',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            margin: '0 auto 24px'
          }}>
            <XCircle size={44} color="var(--danger)" />
          </div>
          <h2 style={{ fontSize: '1.6rem', fontWeight: '800', color: 'var(--danger)', marginBottom: '12px' }}>
            Invalid QR Code
          </h2>
          <p style={{ color: 'var(--text-muted)', marginBottom: '32px', lineHeight: '1.6' }}>
            This QR code could not be verified. It may be corrupted, expired, or not generated by SmartCampus.
          </p>
          <button className="btn btn-outline" onClick={() => navigate('/bookings/my')} style={{ padding: '12px 28px' }}>
            <ArrowLeft size={16} /> Back to My Bookings
          </button>
        </div>
      </div>
    );
  }

  // ─────────────────────────────────────────────
  // LOADING STATE
  // ─────────────────────────────────────────────
  if (!booking) {
    return (
      <div style={{ minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
        <p style={{ color: 'var(--text-muted)', fontSize: '1.1rem' }}>Verifying booking...</p>
      </div>
    );
  }

  // ─────────────────────────────────────────────
  // VALID BOOKING RECEIPT
  // ─────────────────────────────────────────────
  return (
    <div style={{
      minHeight: '100vh',
      background: 'var(--bg)',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      padding: '32px 16px'
    }}>
      <div style={{
        width: '100%',
        maxWidth: '520px',
      }}>

        {/* ── Header Brand ── */}
        <div style={{ textAlign: 'center', marginBottom: '28px' }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '10px', marginBottom: '8px' }}>
            <GraduationCap size={32} color="var(--primary)" />
            <span style={{ fontSize: '1.4rem', fontWeight: '800', color: 'var(--primary)' }}>SmartCampus</span>
          </div>
          <p style={{ color: 'var(--text-muted)', fontSize: '0.95rem' }}>Booking Verification System</p>
        </div>

        {/* ── Receipt Card ── */}
        <div style={{
          background: 'var(--surface)',
          borderRadius: '28px',
          boxShadow: 'var(--shadow-lg)',
          border: '1px solid var(--border)',
          overflow: 'hidden'
        }}>

          {/* ── Green Header Strip ── */}
          <div style={{
            background: 'linear-gradient(135deg, var(--primary) 0%, var(--primary-dark) 100%)',
            padding: '32px',
            textAlign: 'center',
            color: 'white'
          }}>
            <div style={{
              background: 'rgba(255,255,255,0.2)',
              width: '72px',
              height: '72px',
              borderRadius: '50%',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              margin: '0 auto 16px'
            }}>
              <CheckCircle2 size={44} color="white" />
            </div>
            <h1 style={{ fontSize: '1.5rem', fontWeight: '800', marginBottom: '8px' }}>
              Booking Verified Successfully
            </h1>
            <div style={{
              display: 'inline-flex',
              alignItems: 'center',
              gap: '6px',
              background: 'rgba(255,255,255,0.2)',
              padding: '6px 18px',
              borderRadius: '999px',
              fontSize: '0.85rem',
              fontWeight: '700',
              letterSpacing: '1px'
            }}>
              <ShieldCheck size={15} /> VALID BOOKING
            </div>
          </div>

          {/* ── Dotted Divider (receipt effect) ── */}
          <div style={{
            borderTop: '2px dashed var(--border)',
            margin: '0 24px',
          }} />

          {/* ── Receipt Body ── */}
          <div style={{ padding: '32px' }}>
            <h2 style={{
              fontSize: '1.1rem',
              fontWeight: '700',
              color: 'var(--text-main)',
              marginBottom: '24px',
              textAlign: 'center',
              letterSpacing: '0.5px'
            }}>
              BOOKING VERIFICATION PASS
            </h2>

            <div style={{ display: 'flex', flexDirection: 'column', gap: '18px' }}>

              {/* Booking ID */}
              <div style={{ display: 'flex', alignItems: 'center', gap: '14px', padding: '14px 16px', background: 'var(--surface-hover)', borderRadius: '12px' }}>
                <div style={{ color: 'var(--primary)', flexShrink: 0 }}>
                  <Hash size={22} />
                </div>
                <div>
                  <div style={{ fontSize: '0.78rem', color: 'var(--text-muted)', fontWeight: '600', textTransform: 'uppercase', letterSpacing: '0.5px', marginBottom: '2px' }}>Booking ID</div>
                  <div style={{ fontWeight: '700', fontSize: '1.05rem', color: 'var(--text-main)' }}>#{booking.bookingId}</div>
                </div>
              </div>

              {/* Resource Type */}
              <div style={{ display: 'flex', alignItems: 'center', gap: '14px', padding: '14px 16px', background: 'var(--surface-hover)', borderRadius: '12px' }}>
                <div style={{ color: 'var(--primary)', flexShrink: 0 }}>
                  <Layers size={22} />
                </div>
                <div>
                  <div style={{ fontSize: '0.78rem', color: 'var(--text-muted)', fontWeight: '600', textTransform: 'uppercase', letterSpacing: '0.5px', marginBottom: '2px' }}>Resource Type</div>
                  <div style={{ fontWeight: '700', fontSize: '1.05rem', color: 'var(--text-main)' }}>{booking.resourceType || 'Resource'}</div>
                </div>
              </div>

              {/* Resource Name */}
              <div style={{ display: 'flex', alignItems: 'center', gap: '14px', padding: '14px 16px', background: 'var(--surface-hover)', borderRadius: '12px' }}>
                <div style={{ color: 'var(--primary)', flexShrink: 0 }}>
                  <Building2 size={22} />
                </div>
                <div>
                  <div style={{ fontSize: '0.78rem', color: 'var(--text-muted)', fontWeight: '600', textTransform: 'uppercase', letterSpacing: '0.5px', marginBottom: '2px' }}>Resource Name</div>
                  <div style={{ fontWeight: '700', fontSize: '1.05rem', color: 'var(--text-main)' }}>{booking.resourceName}</div>
                </div>
              </div>

              {/* Date */}
              <div style={{ display: 'flex', alignItems: 'center', gap: '14px', padding: '14px 16px', background: 'var(--surface-hover)', borderRadius: '12px' }}>
                <div style={{ color: 'var(--primary)', flexShrink: 0 }}>
                  <Calendar size={22} />
                </div>
                <div>
                  <div style={{ fontSize: '0.78rem', color: 'var(--text-muted)', fontWeight: '600', textTransform: 'uppercase', letterSpacing: '0.5px', marginBottom: '2px' }}>Date</div>
                  <div style={{ fontWeight: '700', fontSize: '1.05rem', color: 'var(--text-main)' }}>{booking.date}</div>
                </div>
              </div>

              {/* Time Slot */}
              <div style={{ display: 'flex', alignItems: 'center', gap: '14px', padding: '14px 16px', background: 'var(--surface-hover)', borderRadius: '12px' }}>
                <div style={{ color: 'var(--primary)', flexShrink: 0 }}>
                  <Clock size={22} />
                </div>
                <div>
                  <div style={{ fontSize: '0.78rem', color: 'var(--text-muted)', fontWeight: '600', textTransform: 'uppercase', letterSpacing: '0.5px', marginBottom: '2px' }}>Time Slot</div>
                  <div style={{ fontWeight: '700', fontSize: '1.05rem', color: 'var(--text-main)' }}>
                    {booking.startTime} &nbsp;→&nbsp; {booking.endTime}
                  </div>
                </div>
              </div>

            </div>
          </div>

          {/* ── Dotted Divider ── */}
          <div style={{ borderTop: '2px dashed var(--border)', margin: '0 24px' }} />

          {/* ── Footer Actions ── */}
          <div style={{ padding: '24px 32px', display: 'flex', gap: '12px', justifyContent: 'center', flexWrap: 'wrap' }}>
            <button
              className="btn btn-outline"
              onClick={() => navigate('/bookings/my')}
              style={{ padding: '12px 24px' }}
            >
              <ArrowLeft size={16} /> Back to Dashboard
            </button>
            <button
              className="btn btn-primary"
              onClick={handlePrint}
              style={{ padding: '12px 24px' }}
            >
              <Printer size={16} /> Print Receipt
            </button>
          </div>

        </div>

        {/* ── Footer Note ── */}
        <p style={{ textAlign: 'center', fontSize: '0.8rem', color: 'var(--text-muted)', marginTop: '20px' }}>
          This pass was generated by SmartCampus Booking System. Present this to campus staff for entry.
        </p>
      </div>
    </div>
  );
}
