# --- Database Connection Settings (XAMPP MySQL) ---
# ?createDatabaseIfNotExist=true tells Spring to make the database for you automatically!
spring.datasource.url=jdbc:mysql://localhost:3306/smartcampus_db?createDatabaseIfNotExist=true

# XAMPP's default username is 'root'
spring.datasource.username=root

# XAMPP's default password is completely blank, so leave nothing after the equals sign!
spring.datasource.password=

# --- Hibernate / JPA Settings ---
# 'update' tells Spring to automatically create your database tables based on your Java Entities
spring.jpa.hibernate.ddl-auto=update

# This prints the SQL queries in your terminal so you can see what Spring is doing
spring.jpa.show-sql=true

# --- Server Settings ---
server.port=8082